name: Load Parameters
description: |
  This composite action loads build parameters from a `MACHINES.json` file.
  It parses the JSON file to create two matrices:
  build_matrix: A slimmed-down matrix containing only 'machine' and 'firmware' for better visibility in job names.
  full_matrix: A complete matrix including 'machine', 'firmware', and 'lavaname' for passing all necessary details to test jobs.
  It expects the `MACHINES.json` file to be located at `ci/MACHINES.json` relative to the workspace root.
  Each entry in `MACHINES.json` should be a key-value pair where the key is the machine name
  and the value is an array `[firmware, lavaname]`.

outputs:
  build_matrix:
    description: Build matrix (machine, firmware) for job naming
    value: ${{ steps.set-matrix.outputs.build_matrix }}

  full_matrix:
    description: Full matrix (machine, firmware, lavaname) for test job details
    value: ${{ steps.set-matrix.outputs.full_matrix }}

runs:
  using: "composite"
  steps:
    - name: Set Build Matrix
      id: set-matrix
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const filePath = path.join(process.env.GITHUB_WORKSPACE, 'ci', 'MACHINES.json');
          let machinesData;

          try {
            if (!fs.existsSync(filePath)) {
              core.setFailed(`Error: MACHINES.json not found at ${filePath}`);
              return;
            }
            machinesData = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
          } catch (err) {
            core.setFailed(`Failed to load or parse MACHINES.json: ${err.message}`);
            return;
          }

          // Validate the structure of machinesData
          if (typeof machinesData !== 'object' || machinesData === null) {
            core.setFailed('Error: MACHINES.json content is not a valid JSON object.');
            return;
          }
          // Slim matrix for better job visibility (machine, firmware)
          const slim_matrix = [];
          // Full matrix to pass to test jobs (machine, firmware, lavaname)
          const complete_matrix = [];

          for (const machineName of Object.keys(machinesData)) {
            const params = machinesData[machineName];

            if (!Array.isArray(params) || params.length !== 2) {
              core.setFailed(`Error: Invalid entry for machine "${machineName}" in MACHINES.json. Expected an array of [firmware, lavaname].`);
              return;
            }

            const [firmware, lavaname] = params;

            if (typeof firmware !== 'string' || typeof lavaname !== 'string') {
              core.setFailed(`Error: Invalid data types for machine "${machineName}". Firmware and lavaname must be strings.`);
              return;
            }

            slim_matrix.push({ machine: machineName, firmware: firmware });
            complete_matrix.push({ machine: machineName, firmware: firmware, lavaname: lavaname });
          }

          if (Object.keys(machinesData).length === 0) {
            core.setWarning('MACHINES.json is empty. No matrices will be generated.');
          }
          core.setOutput('build_matrix', JSON.stringify(slim_matrix));
          console.log('Generated build_matrix:', JSON.stringify(slim_matrix, null, 2));
          core.setOutput('full_matrix', JSON.stringify(complete_matrix));
          console.log('Generated full_matrix:', JSON.stringify(complete_matrix, null, 2));
